only_rules:
  - colon
  - operator_usage_whitespace
  - return_arrow_whitespace
  - trailing_whitespace
  - vertical_whitespace
  - void_return
  - custom_rules

excluded:
  - Core/Sources/Scenarios
  - Core/Sources/TestSupport
  - Core/Tests

colon:
  apply_to_dictionaries: false

custom_rules:
  base_class_required: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    name: "Base class required" # rule name. optional.
    regex: "(UILabel|UITextField|UINavigationController)" # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    match_kinds: # SyntaxKinds to match. optional.
      - identifier
    message: "Use prefix `Base` instead of `UI` for this type" # violation message. optional.
    severity: error # violation severity. optional.
  localization_key_with_wls_suffix_is_forbidden:
    included: "Core/Sources/Localization/StringLocalizableKey.swift"
    name: "Case identifier with _wls suffix is forbidden"
    regex: "^ *case [^ ]+_wls"
    message: "Keys with a _wls suffix are dynamically created when using a localizeForCountry method with the same existing key, without the suffix, as an argument."
    severity: error
